### ISSUE TITLE
Misc.resource usage

### ISSUE THREAD

**Issue by samo790** [krabobmkd/amigamame#14]
Just tried to run the Mame test exe on my Sam440 with OS4, but apparently it need misc.resource
As far as i know misc.resource is availible also on OS4, but only on classic machines!
Is that really mandatory?
Could we get rid of its usage?

**Comment by krabobmkd** [comment]
Hello, Thank you for your tests.
I didn't even know OS4 could run 68000 codes , that's great.

You are totally right: this version search for misc.resource because of native Amiga classic  parrallel port extra joysticks, and it should do that only if this is configured, and should not quit on failure. I bet this has to do with the GCC "implicit initialisations" system. I'll have a look.

 That said, running on OS4 could take profit of the "ScalePixelArray()" and triple buffers functions, that are not complete on the current pistorm picasso drivers.

**Comment by samo790** [comment]
Yes, the input system used on AmigaOS4 is called AmigaInput and it also include a method to patch" the lowlevel to declare as USB pads ...  as far as to be compatible CD32 pads is a metter to be seen :-)

**Comment by krabobmkd** [comment]
Great.
You may test version  Beta3b I've just released: Misc resource and parallel ports "should" be optional if present. Yet something else could block the OS4 run... I don't know.

[https://github.com/krabobmkd/amigamame/releases/download/beta3b/Mame106MiniMixBeta3b.lha](https://github.com/krabobmkd/amigamame/releases/download/beta3b/Mame106MiniMixBeta3b.lha)

**Comment by samo790** [comment]
Ok, tested the latest binary from RAM, by try launching the preset rom game you included into the archive

It crash on both double only click only on Mame exe, or by instead starting it from shell by also trying to load the rom from its path

[Crashlog_Mame106_2024-09-17_16-51-52.txt](https://github.com/user-attachments/files/17029873/Crashlog_Mame106_2024-09-17_16-51-52.txt)

**Comment by krabobmkd** [comment]
Thanks for the log but I coul'nt get anything from it.  So if the GUI is not reached, something on the init does that. You may try to run a command line with just "Mame106 arkcrsn5" to try to directly load the rom, without the path. This just squeeze the MUI part. I'll try to do a log version if you are still interested in "debugging by dichotomy " :)

**Comment by samo790** [comment]
Hi mate,

Just tried to put the rom file into the main directory as you suggest, the
relaunched from shell.... but got the same crash

Still crashed at startup even by try to starting the Mame106 exe
standalone, on both double click on its icon or via command line

Also tried from shell:

Mame106 -help

It crashed aswell :-(

Same with -nosound option

Thanks for the log but I coul'nt get anything from it. So if the GUI is not

**Comment by samo790** [comment]
Is current binary compiled specifically for 68060 + 68882 FPU ?
Not sure if this may create problem under emulation on OS4

**Comment by samo790** [comment]
Btw, is the MorphOS version be any usefull for you?
Its GUI is based on MUI aswell and it contain some optimized code parts that maybe could be reused in your port

http://fabportnawak.free.fr/mame/

**Comment by krabobmkd** [comment]
Hello, you may try Beta3c, that outputs all the init sequence, so we may find out the cause of the OS4 crash.
https://github.com/krabobmkd/amigamame/releases/download/beta3c/Mame106MiniMixBeta3c.lha

**Comment by samo790** [comment]
Ok here the shell output i have just before the crash:

Processo: Shell 4
4.AmigaOS4:> System:Giochi/Mame106/ 
4.System:Giochi/Mame106> Mame106 arkcrsn5.zip
hello
Open graphics 39
Open intuition 39
Open utility 0
Open keymap 36
Open asl 36
Open lowlevel 0
Open cybergraphics 1
Open gadtools 1
gadtools_init
misc resource
initTimers
gui_gadtools_init()
getMainConfig().init()


[Crashlog_Mame106_2024-09-26_19-36-10.txt](https://github.com/user-attachments/files/17152944/Crashlog_Mame106_2024-09-26_19-36-10.txt)

**Comment by krabobmkd** [comment]
Hello, You may try beta3d, which have more logs at the crashing points.
Yes, dichotomy debugging is ridiculous. At this point there is some C++ object construtors and a loop that collects informations from a table and construct namesin another table. I recoded more explicitly these constructors, it may be a compiler issue or an allocation not doing the right thing,...

[https://github.com/krabobmkd/amigamame/releases/tag/beta3d](https://github.com/krabobmkd/amigamame/releases/tag/beta3d)

**Comment by samo790** [comment]
Just tried beta3d, but i have another break

Processo: Shell 4
4.AmigaOS4:> System:Giochi/Mame106/
4.System:Giochi/Mame106> Mame106 arkcrsn5.zip
hello
Open graphics 39
Open intuition 39
Open utility 0
Open keymap 36
Open asl 36
Open lowlevel 0
Open cybergraphics 1
Open gadtools 1
gadtools_init
misc resource
initTimers
gui_gadtools_init()
getMainConfig().init()
MameConfig::Display::Display()
MameConfig::Audio::Audio()
MameConfig::Controls::Controls()
MameConfig::Misc::Misc()
MameConfig::Help::Help()
MameConfig::MameConfig()
initDriverIndex() 1

Then it crash --> crashlog attached

[Crashlog_Mame106_2024-10-17_08-16-45.txt](https://github.com/user-attachments/files/17406764/Crashlog_Mame106_2024-10-17_08-16-45.txt)

**Comment by samo790** [comment]
Any news about this?
Tested the latest beta 4 but still got an instant crash at startup:-/

[Crashlog_Mame106_2024-12-02_00-35-15.txt](https://github.com/user-attachments/files/17970678/Crashlog_Mame106_2024-12-02_00-35-15.txt)

**Comment by krabobmkd** [comment]
... For the record it seems the OS4 emulated crash came from a c++ map<string,struct> init nested in a constructor. Yet, works either in UEA or Emu68. If this happens, it is likely to happen again on another C++ constructor. I think there is sometimes problem in GCC6.5 68k bebbo for values returned by d0 and its ccr flags. not sure. I can't do more at that point.

**Comment by samo790** [comment]
For next version could you maybe reintroduce the log output also for the non-debug binary?
I think it will be pretty usefull for end users, even something toggable on/off would be nice
Aniway any chance for you to install a copy of AmigaOS4 for testing? 
Maybe under UAE

**Comment by samo790** [comment]
Any news on this?

**Comment by krabobmkd** [comment]
@samo790  Well, no.  Considering it works on all UAE JIT, emu68, and real 68060 with MMU, I guess the problem comes from the OS4 68k emulation. Maybe it just doesnt manage double float, which needs particularly the 68060 FPU I guess, or one unique 68k instruction not managed. Having 680x0 executable using these specs are rare, they may just never tested that, or just don't support some 68060 special instruction set. You may try to contact the OS4 68k emulation developer about it.

Then realise the whole point of "Minimix" is to optimize some "106" version so it would match the emu68 speed. There is "really no need for it" on powerpc, which has multiple MAME ports, there is even a Mame 151 ports on os4depot (with way more games and capcom CPS3 support), with no need for 68k->ppc emulation.

**Comment by samo790** [comment]
The feature set of the internal 68k emulation is here: https://www.amiga.hu/amigos/rachy/petunia.html

Yes it is true that there are several ports of Mame on OS4, the problem is that they are entirely based on SDL, therefore extremely slow on low-end machines, such as classic Amigas with OS4 or even Sam440/460

**Comment by samo790** [comment]
Well well, i have a good news afterall ... after various test i was able to run it!
But it was necessary to disable the Petunia JIT, in this way Mame will runs in 68k interpretive mode provided by the OS4 kernel :-)
Only problem, everything is a lot slower, but atleast functional .... now i can atleast doing some test with it

Btw, maybe you can add a few additional line in documentation:

- In case of problem, before starting Mame106 68k under OS4, disabling the Petunia JIT in --> SYS/Prefs/Compatibility

**Comment by krabobmkd** [comment]
.. no, I am not a OS4 user myself, I can't even install a PPC UAE on my linux, and I don't plan to buy some OS4.2 at all, so it makes no sense I would report a OS4 bug myself. The bug is not in this MAME version, it just helped to identify the petunia bug. You may just post them this thread URL which has all logs and description they need, with a few word really.

**Comment by samo790** [comment]
I just report the issue: https://forum.hyperion-entertainment.com/viewtopic.php?t=5133

I don't expect the problem to be solved anytime soon, but reporting it is already a first step ;-)

**Comment by krabobmkd** [comment]
ok I close here
